### ISSUE TITLE
What are the risks?

### ISSUE THREAD

**Issue by Tashima42** [dianariyanto/virtual-display-linux#22]
A few days @dianariyanto made this commit: https://github.com/dianariyanto/virtual-display-linux/commit/4c5287726c5c138a7b4c87319079a86a4888b226 warning about the risks. 
So... What are the risks? Can I brake my install or something like that? Thanks.

**Comment by dianariyanto** [comment]
As you can see, some users are reporting that this script can kill your X #20. This may be due to differences in hardware specifications, some laptops use LVDS and newer laptops now use EDP as the main display. Or it could be due to differences in GPU devices, as you know this script only works only on Intel GPU devices for now.

If that happened to you, just remove `/usr/share/X11/xorg.conf.d/20-intel.conf` then `reboot` will save you from reinstalling your OS.
